### PR TITLE
Dev

### PR DESCRIPTION
**Pull request by Ferdy233**
Corrections made

### CODE REVIEW

**Review by E-Agbettor — APPROVED** [review]
Well done!

**Comment by E-Agbettor** [comment]
Resolve the conflicts in your code

**Comment by Ferdy233** [comment]
I've done that now please
________________________________
From: Elliot Adinortey Agbettor ***@***.***>
Sent: Thursday, 7 November 2024 07:41
To: Ferdy233/Labs ***@***.***>
Cc: Ferdinald Dogbey ***@***.***>; Author ***@***.***>
Subject: From GithubRe: [Ferdy233/Labs] Dev (PR #1)


Resolve the conflicts in your code

**Comment by E-Agbettor** [comment]
PR review and merged!

**Comment by Ferdy233** [comment]
Thank You

**Pull request merged**
